mfPkg.syncAll({
  "fi": {
    "validation.competition.name": {
      "key": "validation.competition.name",
      "lang": "fi",
      "text": "Täytäppä nimi kans",
      "ctime": 1445001665949,
      "mtime": 1445001665949,
      "revisionId": "hoPLW7qs4tyaWFAik",
      "file": "./lib/collections/competitions.js",
      "line": 9,
      "func": "function (competition)",
      "_id": "goB2NHfsyt5FnTq2x"
    },
    "validation.competition.desc": {
      "key": "validation.competition.desc",
      "lang": "fi",
      "text": "Täytäppä kuvaus kans",
      "ctime": 1445001665949,
      "mtime": 1445001665949,
      "revisionId": "xGjivCfG5wvY3uMe6",
      "file": "./lib/collections/competitions.js",
      "line": 11,
      "func": "function (competition)",
      "_id": "55okwwoztJCsf9u72"
    },
    "validation.competition.closed": {
      "key": "validation.competition.closed",
      "lang": "fi",
      "text": "Sori kilpailu on suljettu",
      "ctime": 1445001665949,
      "mtime": 1445001665949,
      "revisionId": "imMLL74diiKZNEaEC",
      "file": "./lib/collections/competitions.js",
      "line": 19,
      "func": "function(competitionId)",
      "_id": "SZsGJqxeMha8vrEHc"
    },
    "validation.competition.valid": {
      "key": "validation.competition.valid",
      "lang": "fi",
      "text": "Valitse kunnollinen kilpailu",
      "ctime": 1445001665949,
      "mtime": 1445001665949,
      "revisionId": "QxPHj65Jx8TSpYBjk",
      "file": "./lib/collections/competitions.js",
      "line": 26,
      "func": "function(competitionId)",
      "_id": "8D533shhEwBjMmhQK"
    },
    "validation.song.name": {
      "key": "validation.song.name",
      "lang": "fi",
      "text": "Syötäppä nimi",
      "ctime": 1445001665949,
      "mtime": 1445001665949,
      "revisionId": "Z4eNywXjuY6omf9db",
      "file": "./lib/collections/songs.js",
      "line": 5,
      "func": "function (song)",
      "_id": "xq7cekdpJHhvhsBmB"
    },
    "validation.song.uri": {
      "key": "validation.song.uri",
      "lang": "fi",
      "text": "Syötäppä URI tai youtube hash",
      "ctime": 1445001665949,
      "mtime": 1445001665949,
      "revisionId": "pw6i8BYqQrCS8MruF",
      "file": "./lib/collections/songs.js",
      "line": 6,
      "func": "function (song)",
      "_id": "8LwGuZgdxavstM4cD"
    },
    "validation.song.uri.not.valid": {
      "key": "validation.song.uri.not.valid",
      "lang": "fi",
      "text": "Eipä taida olla youtube hash tai spotify URI tämä :(",
      "ctime": 1445001665949,
      "mtime": 1445001665949,
      "revisionId": "mSML6HB7bHDaitPwC",
      "file": "./lib/collections/songs.js",
      "line": 9,
      "func": "function (song)",
      "_id": "RCQHDTZgaJNKRwXxE"
    },
    "validation.song.exists.already": {
      "key": "validation.song.exists.already",
      "lang": "fi",
      "text": "Biisi on jo mukana kilpailussa.",
      "ctime": 1445001665949,
      "mtime": 1445001665949,
      "revisionId": "4JxfNAH3XFGqaG2y5",
      "file": "./lib/collections/songs.js",
      "line": 13,
      "func": "function (song)",
      "_id": "hgMPoc3un48t3ajSa"
    },
    "validation.song.edit.own": {
      "key": "validation.song.edit.own",
      "lang": "fi",
      "text": "Et voi muokata kuin omii biisei.",
      "ctime": 1445001665949,
      "mtime": 1445001665949,
      "revisionId": "Nif7XLfuftBZxqSun",
      "file": "./lib/collections/songs.js",
      "line": 54,
      "func": "function (songAttributes)",
      "_id": "K9r8WhX6eEy5y6fTq"
    },
    "song.edit": {
      "key": "song.edit",
      "lang": "fi",
      "text": "Muokkaa",
      "ctime": 1445001665949,
      "mtime": 1445001665949,
      "revisionId": "Kz9ay7szmjDfBxpFR",
      "file": "./client/templates/songs/song_item.html",
      "line": 6,
      "template": "songItem",
      "_id": "Z277wkWxKhK5dJB3B"
    },
    "song.rating": {
      "key": "song.rating",
      "lang": "fi",
      "text": "Sinun mielipiteesi",
      "ctime": 1445001665949,
      "mtime": 1445001665949,
      "revisionId": "sL2qQv3oSLJpzaP79",
      "file": "./client/templates/songs/song_item.html",
      "line": 17,
      "template": "songItem",
      "_id": "6c2xKmpYbtx6qDaye"
    },
    "song.ratings": {
      "key": "song.ratings",
      "lang": "fi",
      "text": "Tulokset",
      "ctime": 1445001665949,
      "mtime": 1445001665949,
      "revisionId": "w4AA2YBF7jdroSCd8",
      "file": "./client/templates/songs/song_item.html",
      "line": 36,
      "template": "songItem",
      "_id": "BNwp2CbcoMJtn4SgS"
    },
    "song.ratings.name": {
      "key": "song.ratings.name",
      "lang": "fi",
      "text": "Nimi",
      "ctime": 1445001665949,
      "mtime": 1445001665949,
      "revisionId": "NzGxAfDzmn6w9PgKB",
      "file": "./client/templates/songs/song_item.html",
      "line": 41,
      "template": "songItem",
      "_id": "RyXtSTLcQq3ZXGPYX"
    },
    "song.ratings.rating": {
      "key": "song.ratings.rating",
      "lang": "fi",
      "text": "Arvosana",
      "ctime": 1445001665949,
      "mtime": 1445001665949,
      "revisionId": "AmZFpmeBkcS69hjQw",
      "file": "./client/templates/songs/song_item.html",
      "line": 42,
      "template": "songItem",
      "_id": "Hm2DXejWzpWBf3BJT"
    },
    "song.ratings.average": {
      "key": "song.ratings.average",
      "lang": "fi",
      "text": "Yhteensä",
      "ctime": 1445001665949,
      "mtime": 1445001665949,
      "revisionId": "WggNvMBGtbEygWRgy",
      "file": "./client/templates/songs/song_item.html",
      "line": 59,
      "template": "songItem",
      "_id": "AL4icP5uPptvB8Pzz"
    },
    "login.please.text": {
      "key": "login.please.text",
      "lang": "fi",
      "text": "Kirjauduhan sisään tuolta ylhäältä.",
      "ctime": 1445001665949,
      "mtime": 1445001665949,
      "revisionId": "e4xWjzPdAAbX9BjeP",
      "file": "./client/templates/login/login_jumbo.html",
      "line": 2,
      "template": "loginJumbo",
      "_id": "Jyv3y2P9tYpsXAfJX"
    },
    "chat.send.placeholder": {
      "key": "chat.send.placeholder",
      "lang": "fi",
      "text": "Viestisi...",
      "ctime": 1445001665949,
      "mtime": 1445001665949,
      "revisionId": "DqF57HWG6r5t5ygbv",
      "file": "./client/templates/includes/chat.html",
      "line": 28,
      "template": "chat",
      "_id": "MAALvSrkCrcd2T3ur"
    },
    "chat.send.submit": {
      "key": "chat.send.submit",
      "lang": "fi",
      "text": "Lähetä",
      "ctime": 1445001665949,
      "mtime": 1445001665949,
      "revisionId": "aezdWpaiM78jDMXyz",
      "file": "./client/templates/includes/chat.html",
      "line": 30,
      "template": "chat",
      "_id": "gzXXPgFjHTHb7zZS6"
    },
    "competition.users": {
      "key": "competition.users",
      "lang": "fi",
      "text": "Kilpailussa mukana",
      "ctime": 1445001665949,
      "mtime": 1445001665949,
      "revisionId": "8Q46362mR7d6FfMdD",
      "file": "./client/templates/includes/competition_actions.html",
      "line": 16,
      "template": "userPill",
      "_id": "KovsyJKK4fJhoAoGA"
    },
    "competition.add.users": {
      "key": "competition.add.users",
      "lang": "fi",
      "text": "Lisää käyttäjiä kilpailuun",
      "ctime": 1445001665949,
      "mtime": 1445001665949,
      "revisionId": "hqHYGJrXCEpXgsnTX",
      "file": "./client/templates/includes/competition_actions.html",
      "line": 37,
      "template": "userPill",
      "_id": "j5fvt57jRKXpuPLKQ"
    },
    "competition.add.user.label": {
      "key": "competition.add.user.label",
      "lang": "fi",
      "text": "Lisää käyttäjiä kilpailuun",
      "ctime": 1445001665949,
      "mtime": 1445001665949,
      "revisionId": "o3CD3eQZH9T7KZqMf",
      "file": "./client/templates/includes/competition_actions.html",
      "line": 42,
      "template": "userPill",
      "_id": "Z6SGiftmaJaguEjMu"
    },
    "competition.add.user.help": {
      "key": "competition.add.user.help",
      "lang": "fi",
      "text": "Voit lisätä yksittäisen käyttäjän kirjoittamalla @-merkin ja edellisen kilpailun kaikki käyttäjät valitsemalla kilpailun kirjoittamalla !-merkin.",
      "ctime": 1445001665949,
      "mtime": 1445001665949,
      "revisionId": "fLryMvii2c2DAFiwf",
      "file": "./client/templates/includes/competition_actions.html",
      "line": 45,
      "template": "userPill",
      "_id": "sXmbjN9H2ytPseYjj"
    },
    "competition.end": {
      "key": "competition.end",
      "lang": "fi",
      "text": "Päätä kilpailu",
      "ctime": 1445001665949,
      "mtime": 1445001665949,
      "revisionId": "PRxds7KwoRC2cvgxn",
      "file": "./client/templates/includes/competition_actions.html",
      "line": 50,
      "template": "userPill",
      "_id": "E4ideeAcJJxBeiRhy"
    },
    "competition.add.song.title": {
      "key": "competition.add.song.title",
      "lang": "fi",
      "text": "Lisää biisi",
      "ctime": 1445001665949,
      "mtime": 1445001665949,
      "revisionId": "MATGiPWwFZjrnBpMq",
      "file": "./client/templates/includes/competition_actions.html",
      "line": 57,
      "template": "userPill",
      "_id": "8reZHButDDXZeqJJZ"
    },
    "competition.add.song.text": {
      "key": "competition.add.song.text",
      "lang": "fi",
      "text": "Tästä voit lisätä oman hitti biisis mukaan kilpailuun. Lisääminen tukee spotify URI:ja ja youtbe hash:jä, joten antaa palaa.",
      "ctime": 1445001665949,
      "mtime": 1445001665949,
      "revisionId": "uhjEJXqtE3mtHHYAj",
      "file": "./client/templates/includes/competition_actions.html",
      "line": 58,
      "template": "userPill",
      "_id": "ank3nFi8Erv8ohvRK"
    },
    "competition.add.song.uri.label": {
      "key": "competition.add.song.uri.label",
      "lang": "fi",
      "text": "Spotify URI tai youtube hash",
      "ctime": 1445001665949,
      "mtime": 1445001665949,
      "revisionId": "ssP8wBNLWAtbqKWHA",
      "file": "./client/templates/includes/competition_actions.html",
      "line": 66,
      "template": "userPill",
      "_id": "Kj47iXeHjanjf9qcW"
    },
    "competition.add.song.name.label": {
      "key": "competition.add.song.name.label",
      "lang": "fi",
      "text": "Biisin nimi",
      "ctime": 1445001665949,
      "mtime": 1445001665949,
      "revisionId": "EwCWhKTnJQYf5cnRu",
      "file": "./client/templates/includes/competition_actions.html",
      "line": 74,
      "template": "userPill",
      "_id": "had4L7WPQvf9bw8jc"
    },
    "competition.add.song.submit.label": {
      "key": "competition.add.song.submit.label",
      "lang": "fi",
      "text": "Lisää biisi",
      "ctime": 1445001665949,
      "mtime": 1445001665949,
      "revisionId": "ucHqqzaz9aKrsZrnt",
      "file": "./client/templates/includes/competition_actions.html",
      "line": 81,
      "template": "userPill",
      "_id": "gXtS7qQARRDGgKEcw"
    },
    "competition.end.head": {
      "key": "competition.end.head",
      "lang": "fi",
      "text": "Ja voittaja on...",
      "ctime": 1445001665949,
      "mtime": 1445001665949,
      "revisionId": "FCnPREfZweJfNTvbx",
      "file": "./client/templates/includes/competition_end.html",
      "line": 5,
      "template": "competitionEnd",
      "_id": "dFyM32twrvdEgNbaJ"
    },
    "competition.end.text": {
      "key": "competition.end.text",
      "lang": "fi",
      "text": "Onnittelut voittajalle! Hän on selkeesti biisien keisari, sadan päämies, satelliitti helvetin pääperkele. Tsekkaa voitto biisi vielä tästä",
      "ctime": 1445001665949,
      "mtime": 1445001665949,
      "revisionId": "tapL2fTsY2tGSm8PA",
      "file": "./client/templates/includes/competition_end.html",
      "line": 7,
      "template": "competitionEnd",
      "_id": "Ae3Czxt85WZ7GReKo"
    },
    "competition.end.results": {
      "key": "competition.end.results",
      "lang": "fi",
      "text": "Katso kaikki tulokset",
      "ctime": 1445001665949,
      "mtime": 1445001665949,
      "revisionId": "jADpobsPE64pZnfns",
      "file": "./client/templates/includes/competition_end.html",
      "line": 9,
      "template": "competitionEnd",
      "_id": "CJqnxDCPoaq34ZiXF"
    },
    "competition.form.text": {
      "key": "competition.form.text",
      "lang": "fi",
      "text": "Levyraati on...no levyraati. Kutsu ystäväsi kilpailuusi ja äänestäkää kimpassa paras biisi.",
      "ctime": 1445001665949,
      "mtime": 1445001665949,
      "revisionId": "b9RoeeXTk6fbesWNL",
      "file": "./client/templates/includes/competition_form.html",
      "line": 5,
      "template": "competitionForm",
      "_id": "SwNGcZi2Dixmiq8Qu"
    },
    "competition.form.head": {
      "key": "competition.form.head",
      "lang": "fi",
      "text": "Luo uusi kilpailu",
      "ctime": 1445001665949,
      "mtime": 1445001665949,
      "revisionId": "JCqNtx28hR3eskYHg",
      "file": "./client/templates/includes/competition_form.html",
      "line": 8,
      "template": "competitionForm",
      "_id": "DmkDrZuyiyp2Z5NZ7"
    },
    "competition.form.name.label": {
      "key": "competition.form.name.label",
      "lang": "fi",
      "text": "Nimi",
      "ctime": 1445001665949,
      "mtime": 1445001665949,
      "revisionId": "87jR367d6n8bEvTpX",
      "file": "./client/templates/includes/competition_form.html",
      "line": 11,
      "template": "competitionForm",
      "_id": "EeZAuTw6tCsGiJgeb"
    },
    "competition.form.desc.label": {
      "key": "competition.form.desc.label",
      "lang": "fi",
      "text": "Kuvaus",
      "ctime": 1445001665949,
      "mtime": 1445001665949,
      "revisionId": "PoFAo4ShrbwbHP2Dp",
      "file": "./client/templates/includes/competition_form.html",
      "line": 16,
      "template": "competitionForm",
      "_id": "E3jo3ND7Jtrr9vQog"
    },
    "competition.form.submit.label": {
      "key": "competition.form.submit.label",
      "lang": "fi",
      "text": "Luo kilpailu",
      "ctime": 1445001665949,
      "mtime": 1445001665949,
      "revisionId": "mCEwBP3K55zkxnrxN",
      "file": "./client/templates/includes/competition_form.html",
      "line": 23,
      "template": "competitionForm",
      "_id": "M9ZNMHhGMDrcuyL7D"
    },
    "competition.to": {
      "key": "competition.to",
      "lang": "fi",
      "text": "Mee tsekkaan tää...",
      "ctime": 1445001665949,
      "mtime": 1445001665949,
      "revisionId": "j7GrWHTjR2LLEHNBt",
      "file": "./client/templates/competitions/competition_item.html",
      "line": 12,
      "template": "competitionItem",
      "_id": "nGT3hCbCvcBFwSR49"
    },
    "competition.chat.open": {
      "key": "competition.chat.open",
      "lang": "fi",
      "text": "Avaa chat",
      "ctime": 1445001665949,
      "mtime": 1445001665949,
      "revisionId": "PAAvTy9HdprKjwwue",
      "file": "./client/templates/competitions/competition_page.html",
      "line": 7,
      "template": "competitionPage",
      "_id": "uHbKWCpbreahnBKoi"
    },
    "competitions.open": {
      "key": "competitions.open",
      "lang": "fi",
      "text": "Avoimet kilpailut",
      "ctime": 1445001665949,
      "mtime": 1445001665949,
      "revisionId": "Jee5vRhmb6nCT3fBJ",
      "file": "./client/templates/competitions/competitions_list.html",
      "line": 3,
      "template": "competitionsList",
      "_id": "NNsgdqMKuWBrHcESY"
    },
    "competitions.closed": {
      "key": "competitions.closed",
      "lang": "fi",
      "text": "Päättyneet kilpailut",
      "ctime": 1445001665949,
      "mtime": 1445001665949,
      "revisionId": "TKTcqcA8Qo2gcJfKu",
      "file": "./client/templates/competitions/competitions_list.html",
      "line": 9,
      "template": "competitionsList",
      "_id": "LZGrdcLhxhM3zDGrp"
    },
    "footr.imp.by": {
      "key": "footr.imp.by",
      "lang": "fi",
      "text": "Ohjelmointi ",
      "ctime": 1445001665949,
      "mtime": 1445001665949,
      "revisionId": "6fkood2NAYitzk6Pf",
      "file": "./client/templates/application/layout.html",
      "line": 18,
      "template": "levyraatiMainLayout",
      "_id": "kgJbXNuGfQHAKLnbH"
    },
    "footr.fork": {
      "key": "footr.fork",
      "lang": "fi",
      "text": "Hae mut ",
      "ctime": 1445001665949,
      "mtime": 1445001665949,
      "revisionId": "gExXntAbMnWxjSPKe",
      "file": "./client/templates/application/layout.html",
      "line": 19,
      "template": "levyraatiMainLayout",
      "_id": "Pj6q5n6RRQDeGkdyQ"
    },
    "common.loading": {
      "key": "common.loading",
      "lang": "fi",
      "text": "Ladataan...",
      "ctime": 1445001665949,
      "mtime": 1445001665949,
      "revisionId": "Wuo2DaoGZhTn6Pzin",
      "file": "./client/templates/application/loading.html",
      "line": 2,
      "template": "loading",
      "_id": "zxjmPsFbvEehbWEvC"
    }
  },
  "en": {
    "validation.competition.name": {
      "key": "validation.competition.name",
      "lang": "en",
      "text": "Fill in name.",
      "ctime": 1445001989596,
      "mtime": 1445001989596,
      "revisionId": "Aq2M393EkiuK93Da3",
      "_id": "bD9JJR2sPJN96C6fp"
    },
    "validation.competition.desc": {
      "key": "validation.competition.desc",
      "lang": "en",
      "text": "Fill in description",
      "ctime": 1445002032242,
      "mtime": 1445002032242,
      "revisionId": "p9yGYrjyWbSsZ3R9n",
      "_id": "6xL272cAtMKn5YCgg"
    },
    "validation.competition.closed": {
      "key": "validation.competition.closed",
      "lang": "en",
      "text": "Sorry the competition is closed",
      "ctime": 1445002044295,
      "mtime": 1445002044295,
      "revisionId": "TRFqJPQ2kKALTXTWg",
      "_id": "2YsS4v3odSDHBfpcK"
    },
    "validation.competition.valid": {
      "key": "validation.competition.valid",
      "lang": "en",
      "text": "Select a valid competition",
      "ctime": 1445002052864,
      "mtime": 1445002052864,
      "revisionId": "7xTGN9HbkBmM8uakG",
      "_id": "JPnHHg6KiZyDsxMHY"
    },
    "validation.song.name": {
      "key": "validation.song.name",
      "lang": "en",
      "text": "Fill in a name",
      "ctime": 1445002059863,
      "mtime": 1445002059863,
      "revisionId": "P8e7J5uj3k5yRbPaR",
      "_id": "somFsnhw6oR6ga8bs"
    },
    "validation.song.uri": {
      "key": "validation.song.uri",
      "lang": "en",
      "text": "Fill in URI or Youtube hash",
      "ctime": 1445002074598,
      "mtime": 1445002074598,
      "revisionId": "DzdmrkNMqg6gWffgE",
      "_id": "8DW4Y2j3B8NKJJ2vd"
    },
    "validation.song.uri.not.valid": {
      "key": "validation.song.uri.not.valid",
      "lang": "en",
      "text": "This doesn't look like a valid youtube hash or spotify URI",
      "ctime": 1445002096201,
      "mtime": 1445002096201,
      "revisionId": "NunXroAzgaj5GzpDE",
      "_id": "Fdi29kk6DkXZLvN62"
    },
    "validation.song.exists.already": {
      "key": "validation.song.exists.already",
      "lang": "en",
      "text": "The song is already in the competition",
      "ctime": 1445002107646,
      "mtime": 1445002107646,
      "revisionId": "WmM2cAacWuivznshg",
      "_id": "yBChYW3mJmz33wjHF"
    },
    "validation.song.edit.own": {
      "key": "validation.song.edit.own",
      "lang": "en",
      "text": "You can only edit your own songs",
      "ctime": 1445002117673,
      "mtime": 1445002117673,
      "revisionId": "zvQjxWyzgkXwXQ5Kn",
      "_id": "dmGiNmj3riA7sZwSd"
    },
    "song.edit": {
      "key": "song.edit",
      "lang": "en",
      "text": "Edit",
      "ctime": 1445002121442,
      "mtime": 1445002121442,
      "revisionId": "YZNXErmAg6iuZ8GHa",
      "_id": "3RNawLMmjsLaTdfwc"
    },
    "song.rating": {
      "key": "song.rating",
      "lang": "en",
      "text": "Your rating",
      "ctime": 1445002127554,
      "mtime": 1445002127554,
      "revisionId": "Xh9ecAJjzFyxFhM47",
      "_id": "SerakPDK6Ri6PZCi6"
    },
    "song.ratings": {
      "key": "song.ratings",
      "lang": "en",
      "text": "Results",
      "ctime": 1445002130661,
      "mtime": 1445002130661,
      "revisionId": "seAjQYwHWkg5hvx3w",
      "_id": "YEdkWy3SkXzP25zL8"
    },
    "song.ratings.name": {
      "key": "song.ratings.name",
      "lang": "en",
      "text": "Name",
      "ctime": 1445002135571,
      "mtime": 1445002135571,
      "revisionId": "93aYBta8sTribxQYs",
      "_id": "JonWbkmtAccbEXQ2t"
    },
    "song.ratings.rating": {
      "key": "song.ratings.rating",
      "lang": "en",
      "text": "Rating",
      "ctime": 1445002151761,
      "mtime": 1445002151761,
      "revisionId": "LktpGmDj9SLMqXzpA",
      "_id": "orLDMcuNqfZED2C6c"
    },
    "song.ratings.average": {
      "key": "song.ratings.average",
      "lang": "en",
      "text": "Results",
      "ctime": 1445002158160,
      "mtime": 1445002158160,
      "revisionId": "mkrA4zoexZEmoGxwo",
      "_id": "86tTxHjcwf7jz9wWL"
    },
    "login.please.text": {
      "key": "login.please.text",
      "lang": "en",
      "text": "Login from above",
      "ctime": 1445002167949,
      "mtime": 1445002167949,
      "revisionId": "qaP5dJSDSRXSQYpoc",
      "_id": "ScuGLd7jYyZAGyJjE"
    },
    "chat.send.placeholder": {
      "key": "chat.send.placeholder",
      "lang": "en",
      "text": "Message..",
      "ctime": 1445002172332,
      "mtime": 1445002172332,
      "revisionId": "fJj22sB67JbXEzRYT",
      "_id": "ePxwPEh9NjhzP9deC"
    },
    "chat.send.submit": {
      "key": "chat.send.submit",
      "lang": "en",
      "text": "Send",
      "ctime": 1445002174894,
      "mtime": 1445002174894,
      "revisionId": "QPFuobutjFnPnMKk9",
      "_id": "TnFr6RMeN8Dyy7uDJ"
    },
    "competition.users": {
      "key": "competition.users",
      "lang": "en",
      "text": "Users in the competition",
      "ctime": 1445002186984,
      "mtime": 1445002186984,
      "revisionId": "H9Zsb7QLcQQL4pQCn",
      "_id": "FWCHbsp6bpmDMoeWa"
    },
    "competition.add.users": {
      "key": "competition.add.users",
      "lang": "en",
      "text": "Add user to the competition",
      "ctime": 1445002196443,
      "mtime": 1445002196443,
      "revisionId": "zEBMdYkP5ErNKXDTj",
      "_id": "NGaQzuWQggHd4vk2B"
    },
    "competition.add.user.label": {
      "key": "competition.add.user.label",
      "lang": "en",
      "text": "Add user to the competition",
      "ctime": 1445002199025,
      "mtime": 1445002199025,
      "revisionId": "pf6WJ4L56JB8tuajm",
      "_id": "JWBacNC7GJCqTbtY4"
    },
    "competition.add.user.help": {
      "key": "competition.add.user.help",
      "lang": "en",
      "text": "You can select individual users by typing '@'-mark and add multiple users from your previous competition by selecting a competition with '!'-mark.",
      "ctime": 1445002211386,
      "mtime": 1445002211386,
      "revisionId": "KaGvoYcrAPP9AbbT2",
      "_id": "pswu5CC3gQE9gwgjW"
    },
    "competition.end": {
      "key": "competition.end",
      "lang": "en",
      "text": "End competition",
      "ctime": 1445002217763,
      "mtime": 1445002217763,
      "revisionId": "MdLExXj8yX8GJr7Es",
      "_id": "FSij5KneuxM9vzD7N"
    },
    "competition.add.song.title": {
      "key": "competition.add.song.title",
      "lang": "en",
      "text": "Add song",
      "ctime": 1445002221948,
      "mtime": 1445002221948,
      "revisionId": "8ydptp8y69gvPQcYG",
      "_id": "PqLAkA6v8bZXMwfX5"
    },
    "competition.add.song.text": {
      "key": "competition.add.song.text",
      "lang": "en",
      "text": "Here you can add your killer tune to the competition. Currently spotify URIs and youtube hashes are supported. So just go for it and take home the win!",
      "ctime": 1445002229581,
      "mtime": 1445002229581,
      "revisionId": "ykY4st3Criesb6g2w",
      "_id": "tzwZC9tp5ptsvJ82g"
    },
    "competition.add.song.uri.label": {
      "key": "competition.add.song.uri.label",
      "lang": "en",
      "text": "Spotify URI or youtube hash",
      "ctime": 1445002238030,
      "mtime": 1445002238030,
      "revisionId": "RKHwAfWie9rBzQndD",
      "_id": "c6hnop73RcrTeQNdk"
    },
    "competition.add.song.name.label": {
      "key": "competition.add.song.name.label",
      "lang": "en",
      "text": "Song name",
      "ctime": 1445002242152,
      "mtime": 1445002242152,
      "revisionId": "Kgx4gNoEzPzxpBpGB",
      "_id": "npgjniDjyu7zxfBjw"
    },
    "competition.add.song.submit.label": {
      "key": "competition.add.song.submit.label",
      "lang": "en",
      "text": "Add song",
      "ctime": 1445002245552,
      "mtime": 1445002245552,
      "revisionId": "gDXPtDNp3L3uYB7SK",
      "_id": "3dSYbwbnfeF29WhZB"
    },
    "competition.end.head": {
      "key": "competition.end.head",
      "lang": "en",
      "text": "And the winner is...",
      "ctime": 1445002251100,
      "mtime": 1445002251100,
      "revisionId": "6BajHSwaeC7iczdQD",
      "_id": "WqhwNQRmvvomF3ooB"
    },
    "competition.end.text": {
      "key": "competition.end.text",
      "lang": "en",
      "text": "Congratulations to the winner! He/She truly knows what's hot right now. You can listen to the winner once again and jam the night away.",
      "ctime": 1445002258323,
      "mtime": 1445002258323,
      "revisionId": "cPXorC9kh9daP5iRp",
      "_id": "6Ew8YoSYkRAz4NG8A"
    },
    "competition.end.results": {
      "key": "competition.end.results",
      "lang": "en",
      "text": "All the results",
      "ctime": 1445002266404,
      "mtime": 1445002266404,
      "revisionId": "qsNShh5ZCW5Gp4vad",
      "_id": "nYZeacdNiaQ5KB5kq"
    },
    "competition.form.text": {
      "key": "competition.form.text",
      "lang": "en",
      "text": "Levyraati is a song voting app where YOU can create your own competitions and invite your friends to join. Together you decide the best song by voting.",
      "ctime": 1445002273142,
      "mtime": 1445002273142,
      "revisionId": "7ZLJpLAjn9mSn4nPj",
      "_id": "NAzAug7Qv4SyKuvBA"
    },
    "competition.form.head": {
      "key": "competition.form.head",
      "lang": "en",
      "text": "Create a new competition",
      "ctime": 1445002281505,
      "mtime": 1445002281505,
      "revisionId": "sYBMFt3EXsGKGpcer",
      "_id": "7Fc2mvZgRtuPyFzmC"
    },
    "competition.form.name.label": {
      "key": "competition.form.name.label",
      "lang": "en",
      "text": "Name",
      "ctime": 1445002284366,
      "mtime": 1445002284366,
      "revisionId": "CwTWSQLPotZabdbMr",
      "_id": "aw9xjbdKgQT3sguFy"
    },
    "competition.form.desc.label": {
      "key": "competition.form.desc.label",
      "lang": "en",
      "text": "Description",
      "ctime": 1445002287807,
      "mtime": 1445002287807,
      "revisionId": "7Z6vQYR6KyuMCLdjD",
      "_id": "FjCMkPHK2CBSNGwRR"
    },
    "competition.form.submit.label": {
      "key": "competition.form.submit.label",
      "lang": "en",
      "text": "Create a competiton",
      "ctime": 1445002296917,
      "mtime": 1445002296917,
      "revisionId": "ZXqyWncT8P9zEjAyp",
      "_id": "hoBo62DnDhNEyuiKe"
    },
    "competition.to": {
      "key": "competition.to",
      "lang": "en",
      "text": "Check this out...",
      "ctime": 1445002305264,
      "mtime": 1445002305264,
      "revisionId": "39hepR5k6FKX87nvg",
      "_id": "GQPPw85axDKHiuDpa"
    },
    "competition.chat.open": {
      "key": "competition.chat.open",
      "lang": "en",
      "text": "Open chat",
      "ctime": 1445002308705,
      "mtime": 1445002308705,
      "revisionId": "J4nxtna2Pza7ZAogs",
      "_id": "NQYdrAv6WaCzC9ie2"
    },
    "competitions.open": {
      "key": "competitions.open",
      "lang": "en",
      "text": "Open competitions",
      "ctime": 1445002313765,
      "mtime": 1445002313765,
      "revisionId": "T5DXHyoJXbs3N5N62",
      "_id": "rfZu7JDF8duovtmcd"
    },
    "competitions.closed": {
      "key": "competitions.closed",
      "lang": "en",
      "text": "Closed competitions",
      "ctime": 1445002318629,
      "mtime": 1445002318629,
      "revisionId": "tZgHEBrCo9psaw4GW",
      "_id": "cWExvqhoTLWnre9Lb"
    },
    "footr.imp.by": {
      "key": "footr.imp.by",
      "lang": "en",
      "text": "Implemented by",
      "ctime": 1445002326081,
      "mtime": 1445002326081,
      "revisionId": "K49pRamjGkZCkwp9d",
      "_id": "jFopjX7WutKADfEu8"
    },
    "footr.fork": {
      "key": "footr.fork",
      "lang": "en",
      "text": "Check me out",
      "ctime": 1445002331861,
      "mtime": 1445002331861,
      "revisionId": "gomNsgczhgwftXKMm",
      "_id": "wRwNX8fBSZNkdK68w"
    },
    "common.loading": {
      "key": "common.loading",
      "lang": "en",
      "text": "Loading...",
      "ctime": 1445002352296,
      "mtime": 1445002352296,
      "revisionId": "DSEzL8ToKqysEQpkd",
      "_id": "hpT3JF3CkFaZfZtcA"
    }
  }
}, {
  "exportedAt": 1445002355209,
  "updatedAt": 1445002352296
});